//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDB_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.AssignedTo = new HashSet<AssignedTo>();
            this.Branch = new HashSet<Branch>();
        }

        [DisplayName("Asset ID")]
        public int id { get; set; }

        [DisplayName("Tangible")]
        public bool isTangible { get; set; }

        [DisplayName("Category")]
        public string category { get; set; }

        [DisplayName("Asset Type")]
        public string assetType { get; set; }

        [DisplayName("Asset Name")]
        public string assetName { get; set; }

        [DisplayName("Asset Description")]
        public string assetDescription { get; set; }

        [DisplayName("Asset State")]
        public string assetState { get; set; }

        [DisplayName("Asset Location")]
        public string assetLocation { get; set; }

        [DisplayName("Acquisition Value")]
        public Nullable<int> acquisitionValue { get; set; }

        [DisplayName("Warranty Time")]
        public Nullable<int> warrantyTime { get; set; }

        [DisplayName("Asset Life Time")]
        public Nullable<int> assetLifeTime { get; set; }

        [DisplayName("Depracation")]
        public Nullable<int> deprecation { get; set; }

        [DisplayName("Salvage Value")]
        public Nullable<int> salvageValue { get; set; }

        [DisplayName("Acquisition Date")]
        public Nullable<System.DateTime> acquisitionDate { get; set; }

        [DisplayName("Registration Date")]
        public Nullable<System.DateTime> registrationDate { get; set; }

        [DisplayName("Picture")]
        public byte[] picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignedTo> AssignedTo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch> Branch { get; set; }
    }
}
