//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDB_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class AssignedTo
    {
        [DisplayName("Asset ID")]
        public int assetId { get; set; }

        [DisplayName("Employee ID")]
        public int employeeID { get; set; }

        [DisplayName("Assignation Date")]
        public Nullable<System.DateTime> assignationDate { get; set; }

        [DisplayName("Branch ID")]
        public Nullable<int> branchID { get; set; }

        [DisplayName("Assignation Location")]
        public string assignationLocation { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
