//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDB_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.AssignedTo = new HashSet<AssignedTo>();
            this.ManagesBranch = new HashSet<ManagesBranch>();
            this.WorksAt = new HashSet<WorksAt>();
            this.Asset = new HashSet<Asset>();
        }

        [DisplayName("Branch ID")]
        public int id { get; set; }

        [DisplayName("Branch Name")]
        public string branchName { get; set; }

        [DisplayName("Branch Description")]
        public string branchDescription { get; set; }

        [DisplayName("Province")]
        public string province { get; set; }

        [DisplayName("Canton")]
        public string canton { get; set; }

        [DisplayName("District")]
        public string district { get; set; }

        [DisplayName("Branch Location")]
        public string branchLocation { get; set; }

        [DisplayName("Branch State")]
        public string branchState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignedTo> AssignedTo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagesBranch> ManagesBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorksAt> WorksAt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Asset { get; set; }
    }
}
