//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDB_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AssignedTo = new HashSet<AssignedTo>();
            this.ManagesBranch = new HashSet<ManagesBranch>();
            this.UserLogin = new HashSet<UserLogin>();
            this.WorksAt = new HashSet<WorksAt>();
        }

        [DisplayName("Employee ID")]
        public int id { get; set; }

        [DisplayName("First Name")]
        public string firstName { get; set; }

        [DisplayName("Middle Name")]
        public string middleName { get; set; }

        [DisplayName("Last Name 1")]
        public string lastName1 { get; set; }

        [DisplayName("Last Name 2")]
        public string lastName2 { get; set; }

        [DisplayName("Birth Date")]
        public Nullable<System.DateTime> birthDate { get; set; }

        [DisplayName("Employee State")]
        public string employeeState { get; set; }

        [DisplayName("Start Date")]
        public Nullable<System.DateTime> startDate { get; set; }

        [DisplayName("Picture")]
        public byte[] picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignedTo> AssignedTo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagesBranch> ManagesBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLogin> UserLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorksAt> WorksAt { get; set; }
    }
}
