//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDB_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ManagesBranch
    {
        [DisplayName("Manager ID")]
        public int managerId { get; set; }

        [DisplayName("Start Date")]
        public Nullable<System.DateTime> startDate { get; set; }

        [DisplayName("Branch ID")]
        public int branchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
