//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDB_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class UserLogin
    {
        [DisplayName("Username")]
        public string username { get; set; }

        [DisplayName("Password")]
        public string userPassword { get; set; }

        [DisplayName("Employee ID")]
        public Nullable<int> employeeID { get; set; }

        [DisplayName("Access Level")]
        public int accessLevel { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
